// src/ai/ai.service.ts
import { Injectable, BadRequestException } from '@nestjs/common';
import Groq from 'groq-sdk';

@Injectable()
export class AiService {
  private groq: Groq;

  constructor() {
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) throw new Error('Missing GROQ_API_KEY in .env');
    this.groq = new Groq({ apiKey });
  }

  // Summarize resume/project text
  async summarize(text: string): Promise<string> {
    if (!text || !text.trim()) throw new BadRequestException('Text cannot be empty');

    try {
      const response = await this.groq.chat.completions.create({
        model: 'llama-3.3-70b-versatile',
        max_tokens: 300,
        messages: [
          {
            role: 'user',
            content: `Summarize the following resume/project text into 3-5 concise bullet points focusing on key achievements and skills. Keep each bullet short and impactful:\n\n${text}`,
          },
        ],
      });

      const summary = response.choices?.[0]?.message?.content || '';
      if (!summary) throw new BadRequestException('No summary generated');

      return summary.trim();
    } catch (err: any) {
      console.error('Groq API error:', err);
      throw new BadRequestException('AI service error: ' + err.message);
    }
  }

  // Score resume text against job keywords/description
  async scoreMatch(resumeText: string, jobKeywords: string): Promise<number> {
    if (!resumeText || !jobKeywords) throw new BadRequestException('Both resumeText and jobKeywords are required');

    try {
      const response = await this.groq.chat.completions.create({
        model: 'llama-3.3-70b-versatile',
        max_tokens: 150,
        messages: [
          {
            role: 'user',
            content: `
You are an expert recruiter AI.

Given the following job description/keywords:
"${jobKeywords}"

And the following candidate resume/profile text:
"${resumeText}"

Please output a single number between 0 and 100 indicating how well this candidate matches the job requirements. Only output the number.`
          }
        ]
      });

      const rawScore = response.choices?.[0]?.message?.content || '';
      const score = parseInt(rawScore.replace(/[^0-9]/g, ''), 10);

      if (isNaN(score) || score < 0 || score > 100) {
        throw new BadRequestException('Invalid score generated by AI');
      }

      return score;
    } catch (err: any) {
      console.error('Groq AI scoring error:', err);
      throw new BadRequestException('AI service error: ' + err.message);
    }
  }

  // Optional: summarize + score in one call
  async summarizeAndScore(resumeText: string, jobKeywords: string) {
    const summary = await this.summarize(resumeText);
    const score = await this.scoreMatch(resumeText, jobKeywords);
    return { summary, score };
  }
}
